In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.decomposition import PCA

In [3]:
data = pd.read_csv('./data/equip_failures_training_set.csv')

In [4]:
data.head()

,id,target,sensor1_measure,sensor2_measure,sensor3_measure,sensor4_measure,sensor5_measure,sensor6_measure,sensor7_histogram_bin0,sensor7_histogram_bin1,...,sensor105_histogram_bin2,sensor105_histogram_bin3,sensor105_histogram_bin4,sensor105_histogram_bin5,sensor105_histogram_bin6,sensor105_histogram_bin7,sensor105_histogram_bin8,sensor105_histogram_bin9,sensor106_measure,sensor107_measure
0,1,0,76698,na,2130706438,280,0,0,0,0,...,1240520,493384,721044,469792,339156,157956,73224,0,0,0
1,2,0,33058,na,0,na,0,0,0,0,...,421400,178064,293306,245416,133654,81140,97576,1500,0,0
2,3,0,41040,na,228,100,0,0,0,0,...,277378,159812,423992,409564,320746,158022,95128,514,0,0
3,4,0,12,0,70,66,0,10,0,0,...,240,46,58,44,10,0,0,0,4,32
4,5,0,60874,na,1368,458,0,0,0,0,...,622012,229790,405298,347188,286954,311560,433954,1218,0,0

In [6]:
data.shape

(60000, 172)

In [5]:
data.columns

Index(['id', 'target', 'sensor1_measure', 'sensor2_measure', 'sensor3_measure',
       'sensor4_measure', 'sensor5_measure', 'sensor6_measure',
       'sensor7_histogram_bin0', 'sensor7_histogram_bin1',
       ...
       'sensor105_histogram_bin2', 'sensor105_histogram_bin3',
       'sensor105_histogram_bin4', 'sensor105_histogram_bin5',
       'sensor105_histogram_bin6', 'sensor105_histogram_bin7',
       'sensor105_histogram_bin8', 'sensor105_histogram_bin9',
       'sensor106_measure', 'sensor107_measure'],
      dtype='object', length=172)

In [7]:
data.target.value_counts()

0    59000
1     1000
Name: target, dtype: int64

In [9]:
data = data.replace('na', np.nan)
data.isna().sum()

id                              0
target                          0
sensor1_measure                 0
sensor2_measure             46329
sensor3_measure              3335
sensor4_measure             14861
sensor5_measure              2500
sensor6_measure              2500
sensor7_histogram_bin0        671
sensor7_histogram_bin1        671
sensor7_histogram_bin2        671
sensor7_histogram_bin3        671
sensor7_histogram_bin4        671
sensor7_histogram_bin5        671
sensor7_histogram_bin6        671
sensor7_histogram_bin7        671
sensor7_histogram_bin8        671
sensor7_histogram_bin9        671
sensor8_measure               645
sensor9_measure               629
sensor10_measure              629
sensor11_measure             4400
sensor12_measure              642
sensor13_measure              629
sensor14_measure              642
sensor15_measure              589
sensor16_measure              642
sensor17_measure              589
sensor18_measure             2723
sensor19_measure              629
                            ...
sensor87_measure             4008
sensor88_measure             4009
sensor89_measure              691
sensor90_measure             2724
sensor91_measure             2726
sensor92_measure             2726
sensor93_measure             2726
sensor94_measure             2727
sensor95_measure             2727
sensor96_measure             2726
sensor97_measure             2726
sensor98_measure             2723
sensor99_measure             2724
sensor100_measure            2723
sensor101_measure            2723
sensor102_measure            4007
sensor103_measure           10239
sensor104_measure            9553
sensor105_histogram_bin0      671
sensor105_histogram_bin1      671
sensor105_histogram_bin2      671
sensor105_histogram_bin3      671
sensor105_histogram_bin4      671
sensor105_histogram_bin5      671
sensor105_histogram_bin6      671
sensor105_histogram_bin7      671
sensor105_histogram_bin8      671
sensor105_histogram_bin9      671
sensor106_measure            2724
sensor107_measure            2723
Length: 172, dtype: int64

In [10]:
data.dtypes

id                           int64
target                       int64
sensor1_measure              int64
sensor2_measure             object
sensor3_measure             object
sensor4_measure             object
sensor5_measure             object
sensor6_measure             object
sensor7_histogram_bin0      object
sensor7_histogram_bin1      object
sensor7_histogram_bin2      object
sensor7_histogram_bin3      object
sensor7_histogram_bin4      object
sensor7_histogram_bin5      object
sensor7_histogram_bin6      object
sensor7_histogram_bin7      object
sensor7_histogram_bin8      object
sensor7_histogram_bin9      object
sensor8_measure             object
sensor9_measure             object
sensor10_measure            object
sensor11_measure            object
sensor12_measure            object
sensor13_measure            object
sensor14_measure            object
sensor15_measure            object
sensor16_measure            object
sensor17_measure            object
sensor18_measure            object
sensor19_measure            object
                             ...
sensor87_measure            object
sensor88_measure            object
sensor89_measure            object
sensor90_measure            object
sensor91_measure            object
sensor92_measure            object
sensor93_measure            object
sensor94_measure            object
sensor95_measure            object
sensor96_measure            object
sensor97_measure            object
sensor98_measure            object
sensor99_measure            object
sensor100_measure           object
sensor101_measure           object
sensor102_measure           object
sensor103_measure           object
sensor104_measure           object
sensor105_histogram_bin0    object
sensor105_histogram_bin1    object
sensor105_histogram_bin2    object
sensor105_histogram_bin3    object
sensor105_histogram_bin4    object
sensor105_histogram_bin5    object
sensor105_histogram_bin6    object
sensor105_histogram_bin7    object
sensor105_histogram_bin8    object
sensor105_histogram_bin9    object
sensor106_measure           object
sensor107_measure           object
Length: 172, dtype: object

In [11]:
data.describe(include = 'all')

,id,target,sensor1_measure,sensor2_measure,sensor3_measure,sensor4_measure,sensor5_measure,sensor6_measure,sensor7_histogram_bin0,sensor7_histogram_bin1,...,sensor105_histogram_bin2,sensor105_histogram_bin3,sensor105_histogram_bin4,sensor105_histogram_bin5,sensor105_histogram_bin6,sensor105_histogram_bin7,sensor105_histogram_bin8,sensor105_histogram_bin9,sensor106_measure,sensor107_measure
count,60000.000000,60000.000000,6.000000e+04,13671,56665,45139,57500,57500,59329,59329,...,59329,59329,59329,59329,59329,59329,59329,59329,57276,57277
unique,NaN,NaN,NaN,29,2061,1886,333,418,154,617,...,34488,31711,35188,36288,31795,30469,24213,9724,28,49
top,NaN,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
freq,NaN,NaN,NaN,10977,8752,2009,55543,55476,59133,58587,...,1364,1557,1797,2814,4458,7898,17280,31863,57021,56794
mean,30000.500000,0.016667,5.933650e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,17320.652413,0.128020,1.454301e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,15000.750000,0.000000,8.340000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,30000.500000,0.000000,3.077600e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,45000.250000,0.000000,4.866800e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,60000.000000,1.000000,2.746564e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN